<?php 
include('php/p_index.php');

echo '<!DOCTYPE html>';
echo '<html>';
echo '<head>';
echo '<link rel="stylesheet" href="css/estilos.css">';
echo '<meta charset="utf-8">';
echo '<title>Page Title</title>';
echo '</head>';
echo '<body>';
echo '<div class="capa1">';
echo '<div class="capa2">';
echo '<form action="php/p_index.php" method="post">';
echo '<div class="login">';
echo '<div>';
echo '<label for="email">Email</label>';
echo '<input type="text" id="email" name="email" value="">';
echo '</div>';
echo '<div>';
echo '<label for="contrasenia">Contraseña</label>';
echo '<input type="password" id="contrasenia" name="contrasenia" value="">';
echo '</div>';
echo '<div>';
echo '<button id="iniciar" name="iniciar">Iniciar Sesión</button>';
echo '<a href="registro.php">Registrarme</a>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</body>';
echo '</html>';